title: Hydro - The Discord Bot

# Build settings
theme: minima

jekyll_admin​:
  ​hidden_links​:
    - ​posts​
    - ​pages​
    - ​staticfiles​
    - ​datafiles​
    - ​configuration​
  ​homepage​: ​"​pages​"
  
plugins:
 - jekyll-cms